# Generated by Django 6.0.2 on 2026-02-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusthandle_app', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
