# Generated by Django 6.0.2 on 2026-02-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trusthandle_app', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
